### PR TITLE
Backup instructions.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@jgmize r?

Not sure if we want the deis-backup-service repository into this one. I decided to have it as separate so it can be more generic.

**Comment by jgmize** [comment]
I'd be fine with bringing the backup service into this repo, but if you want to keep it separate how about we make it a mozilla repo?

**Comment by glogiotatidis** [comment]
@jgmize moved the repo to [mozilla](/mozilla/deis-backup-service)

**Comment by jgmize** [comment]
Awesome, thanks :)

**Pull request merged**
