### PR TITLE
Deis backup and restore playbook.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Current status: this completes successfully but the cluster built doesn't work.

**Comment by glogiotatidis** [comment]
Tada! Finally I managed to get this to work:
- Takes a backup of the current cluster
- Restores into a new one

Can be used to upgrade Deis with no downtime :) Tested multiple times with different clusters, including our current production cluster and works beautifully.

@jgmize comments, thoughts?

**Comment by jgmize** [comment]
Awesome, work @glogiotatidis! It's looking great so far, and I'm looking forward to testing it out this afternoon. One thing you might want to to do is replace the instances of `mffos` and `masterfirefoxos.com` in playbook/README.md and playbook/local_variables_dist.yml with something more generic, but that's up to you.

**Comment by glogiotatidis** [comment]
I made local_variables_dist more descriptive and removed the masterfirefoxos and mffos references. Merging this one for now and we update as we go.

Thanks @jgmize

**Pull request merged**
